import type { EvidenceSource } from "@onerhythm/types";

export const evidenceSources: EvidenceSource[] = [
  {
    source_id: "founder-origin-public-v1",
    title: "Why OneRhythm exists",
    source_name: "OneRhythm",
    source_url: "/stories/why-onerhythm-exists",
    classification: "founder_narrative",
    publisher_kind: "founder",
    language: "en-US",
    publish_date: "2026-03-12",
    updated_date: "2026-03-12",
    reviewed_at: "2026-03-12",
    reviewer_ref: "editorial-review",
    review_state: "published",
    authors: ["Matthew Adams"],
    summary:
      "Public founder-origin narrative describing the lived context and product purpose behind OneRhythm.",
    citation: {
      citation_label: "Adams M. Why OneRhythm exists. OneRhythm. 2026.",
    },
  },
  {
    source_id: "campaign-strategy-public-v1",
    title: "Campaign and content strategy",
    source_name: "OneRhythm",
    source_url: "/campaigns/the-weight-you-cant-see",
    classification: "institutional_reference",
    publisher_kind: "onerhythm_editorial",
    language: "en-US",
    publish_date: "2026-03-12",
    updated_date: "2026-03-12",
    reviewed_at: "2026-03-12",
    reviewer_ref: "editorial-review",
    review_state: "published",
    summary:
      "Public strategy summary covering project origin, campaign framing, voice, and launch communication priorities.",
    citation: {
      citation_label: "OneRhythm. Campaign and content strategy. 2026.",
    },
  },
  {
    source_id: "prd-public-v1",
    title: "OneRhythm public PRD",
    source_name: "OneRhythm",
    source_url: "https://github.com/daftpixie/onerhythm/blob/main/docs/prd/README.md",
    classification: "institutional_reference",
    publisher_kind: "onerhythm_editorial",
    language: "en-US",
    publish_date: "2026-03-01",
    reviewed_at: "2026-03-10",
    reviewer_ref: "editorial-board",
    review_state: "published",
    summary:
      "Public product requirements covering the core platform boundary, privacy model, and feature expectations.",
    citation: {
      citation_label: "OneRhythm. Public PRD v1. 2026.",
    },
  },
  {
    source_id: "product-docs-public-v1",
    title: "OneRhythm product docs",
    source_name: "OneRhythm",
    source_url: "https://github.com/daftpixie/onerhythm/blob/main/docs/product/README.md",
    classification: "institutional_reference",
    publisher_kind: "onerhythm_editorial",
    language: "en-US",
    publish_date: "2026-03-01",
    reviewed_at: "2026-03-10",
    reviewer_ref: "editorial-board",
    review_state: "published",
    summary:
      "Public product framing and contributor-facing problem context for OneRhythm.",
    citation: {
      citation_label: "OneRhythm. Product documentation. 2026.",
    },
  },
  {
    source_id: "education-architecture-v1",
    title: "Educational guidance engine v1",
    source_name: "OneRhythm",
    source_url:
      "https://github.com/daftpixie/onerhythm/blob/main/docs/architecture/educational-guidance-engine-v1.md",
    classification: "institutional_reference",
    publisher_kind: "onerhythm_editorial",
    language: "en-US",
    publish_date: "2026-03-01",
    reviewed_at: "2026-03-10",
    reviewer_ref: "research-review",
    review_state: "published",
    summary:
      "Architecture reference explaining the educational-only guidance boundary, source traceability, and prohibited phrasing rules.",
    citation: {
      citation_label: "OneRhythm. Educational guidance engine v1. 2026.",
    },
  },
  {
    source_id: "public-mosaic-architecture-v1",
    title: "Public Heart Mosaic",
    source_name: "OneRhythm",
    source_url:
      "https://github.com/daftpixie/onerhythm/blob/main/docs/architecture/public-mosaic.md",
    classification: "institutional_reference",
    publisher_kind: "onerhythm_editorial",
    language: "en-US",
    publish_date: "2026-03-12",
    reviewed_at: "2026-03-12",
    reviewer_ref: "editorial-board",
    review_state: "published",
    summary:
      "Architecture reference describing the public mosaic boundary, accessibility model, and anonymous metadata surface.",
    citation: {
      citation_label: "OneRhythm. Public Heart Mosaic. 2026.",
    },
  },
  {
    source_id: "community-stories-architecture-v1",
    title: "Community stories",
    source_name: "OneRhythm",
    source_url:
      "https://github.com/daftpixie/onerhythm/blob/main/docs/architecture/community-stories.md",
    classification: "institutional_reference",
    publisher_kind: "onerhythm_editorial",
    language: "en-US",
    publish_date: "2026-03-12",
    reviewed_at: "2026-03-12",
    reviewer_ref: "editorial-board",
    review_state: "published",
    summary:
      "Architecture reference for consent-based community story submission, moderation, and publication boundaries.",
    citation: {
      citation_label: "OneRhythm. Community stories. 2026.",
    },
  },
  {
    source_id: "editorial-content-strategy-v1",
    title: "OneRhythm Content Strategy",
    source_name: "OneRhythm",
    source_url:
      "https://github.com/daftpixie/onerhythm/blob/main/docs/content/OneRhythm%20Content%20Strategy.md",
    classification: "institutional_reference",
    publisher_kind: "onerhythm_editorial",
    language: "en-US",
    publish_date: "2026-03-01",
    reviewed_at: "2026-03-18",
    reviewer_ref: "editorial-review",
    review_state: "published",
    summary:
      "Editorial strategy source covering public evidence framing, mental-health statistic usage, and non-diagnostic publishing guardrails for OneRhythm.",
    citation: {
      citation_label: "OneRhythm. OneRhythm Content Strategy. 2026.",
    },
  },
  {
    source_id: "guideline-acc-af-2023",
    title: "2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of Atrial Fibrillation",
    source_name: "ACC/AHA/ACCP/HRS",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/38043043/",
    classification: "clinical_guideline",
    publisher_kind: "professional_society",
    language: "en-US",
    publish_date: "2023-11-30",
    reviewed_at: "2026-03-13",
    reviewer_ref: "evidence-review-board",
    review_state: "published",
    authors: ["Joglar JA et al."],
    summary:
      "Contemporary atrial fibrillation guideline used in OneRhythm's educational corpus for neutral, non-diagnostic public education.",
    citation: {
      citation_label:
        "Joglar JA, et al. 2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of Atrial Fibrillation. J Am Coll Cardiol. 2024.",
      doi: "10.1016/j.jacc.2023.08.017",
      pmid: "38043043",
      guideline_body: "ACC/AHA/ACCP/HRS",
    },
  },
  {
    source_id: "study-afib-qol-ablation-2024",
    title: "Effect of catheter ablation versus medical therapy on mental health and quality of life in patients with atrial fibrillation",
    source_name: "Journal of Interventional Cardiac Electrophysiology",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/38980445/",
    classification: "peer_reviewed_study",
    publisher_kind: "journal",
    language: "en-US",
    publish_date: "2024-07-15",
    reviewed_at: "2026-03-13",
    reviewer_ref: "evidence-review-board",
    review_state: "published",
    summary:
      "A systematic review and meta-analysis examining mental-health and quality-of-life outcomes after ablation versus medical therapy in atrial fibrillation.",
    citation: {
      citation_label:
        "Effect of catheter ablation versus medical therapy on mental health and quality of life in patients with atrial fibrillation: a systematic review and meta-analysis of randomized controlled trials. J Interv Card Electrophysiol. 2024.",
      doi: "10.1007/s10840-024-01861-4",
      pmid: "38980445",
    },
  },
  {
    source_id: "study-afib-svt-qol-anxiety-2014",
    title: "Differences in quality of life, anxiety and depression in patients with paroxysmal atrial fibrillation and common forms of supraventricular tachycardia",
    source_name: "Indian Pacing and Electrophysiology Journal",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/25408565/",
    classification: "peer_reviewed_study",
    publisher_kind: "journal",
    language: "en-US",
    publish_date: "2014-10-06",
    reviewed_at: "2026-03-13",
    reviewer_ref: "evidence-review-board",
    review_state: "published",
    summary:
      "Quality-of-life and mood study used in OneRhythm's AF and SVT educational corpus to support plain-language discussion of emotional burden.",
    citation: {
      citation_label:
        "Differences in quality of life, anxiety and depression in patients with paroxysmal atrial fibrillation and common forms of atrioventricular reentry supraventricular tachycardias. Indian Pacing Electrophysiol J. 2014.",
      doi: "10.1016/S0972-6292(16)30796-3",
      pmid: "25408565",
    },
  },
  {
    source_id: "study-icd-mood-burden-2023",
    title: "Burden of mood symptoms and disorders in implantable cardioverter defibrillator patients",
    source_name: "Europace",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/37311667/",
    classification: "peer_reviewed_study",
    publisher_kind: "journal",
    language: "en-US",
    publish_date: "2023-06-27",
    reviewed_at: "2026-03-13",
    reviewer_ref: "evidence-review-board",
    review_state: "published",
    summary:
      "A systematic review and meta-analysis of 39,954 ICD patients covering anxiety, depression, PTSD, and the emotional burden around device therapy.",
    citation: {
      citation_label:
        "Burden of mood symptoms and disorders in implantable cardioverter defibrillator patients: a systematic review and meta-analysis of 39 954 patients. Europace. 2023.",
      doi: "10.1093/europace/euad130",
      pmid: "37311667",
    },
  },
  {
    source_id: "guideline-esc-cardiomyopathies-2023",
    title: "2023 ESC Guidelines for the management of cardiomyopathies",
    source_name: "European Society of Cardiology",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/37622657/",
    classification: "clinical_guideline",
    publisher_kind: "professional_society",
    language: "en-US",
    publish_date: "2023-08-26",
    reviewed_at: "2026-03-13",
    reviewer_ref: "evidence-review-board",
    review_state: "published",
    summary:
      "ESC cardiomyopathy guideline used for ARVC and inherited ventricular disease context in OneRhythm's educational corpus.",
    citation: {
      citation_label:
        "Mckenna WJ, et al. 2023 ESC Guidelines for the management of cardiomyopathies. Eur Heart J. 2023.",
      doi: "10.1093/eurheartj/ehad194",
      pmid: "37622657",
      guideline_body: "ESC",
    },
  },
  {
    source_id: "guideline-esc-svt-2019",
    title: "2019 ESC Guidelines for the management of patients with supraventricular tachycardia",
    source_name: "European Society of Cardiology",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/31504425/",
    classification: "clinical_guideline",
    publisher_kind: "professional_society",
    language: "en-US",
    publish_date: "2019-08-31",
    reviewed_at: "2026-03-13",
    reviewer_ref: "evidence-review-board",
    review_state: "published",
    summary:
      "ESC guideline used for SVT context and non-diagnostic educational framing in OneRhythm's evidence system.",
    citation: {
      citation_label:
        "Brugada J, et al. 2019 ESC Guidelines for the management of patients with supraventricular tachycardia. Eur Heart J. 2020.",
      doi: "10.1093/eurheartj/ehz467",
      pmid: "31504425",
      guideline_body: "ESC",
    },
  },
  {
    source_id: "study-vt-ablation-meta-2024",
    title: "Catheter ablation as first-line treatment for ventricular tachycardia in patients with structural heart disease and preserved left ventricular ejection fraction",
    source_name: "Scientific Reports",
    source_url: "https://pubmed.ncbi.nlm.nih.gov/39122752/",
    classification: "peer_reviewed_study",
    publisher_kind: "journal",
    language: "en-US",
    publish_date: "2024-08-09",
    reviewed_at: "2026-03-13",
    reviewer_ref: "evidence-review-board",
    review_state: "published",
    summary:
      "A recent systematic review and meta-analysis used in OneRhythm's VT evidence corpus to ground procedural context without turning it into a personal recommendation.",
    citation: {
      citation_label:
        "Catheter ablation as first-line treatment for ventricular tachycardia in patients with structural heart disease and preserved left ventricular ejection fraction: a systematic review and meta-analysis. Sci Rep. 2024.",
      doi: "10.1038/s41598-024-69467-4",
      pmid: "39122752",
    },
  },
];
